# Base 
FROM ubuntu:22.04

# Update and install Python
RUN apt-get update && \
    apt-get install -y python3 && \
    apt-get clean

# Create app directory
WORKDIR /app

# Copy your Python script into the container
COPY src/main.py .

# Set default command to run Python code
CMD ["python3", "main.py"]
